### ISSUE TITLE
VS code theme

### ISSUE THREAD

**Issue by niemyjski** [SebastianSzturo/firewatch-syntax#2]
Any chance of getting this theme made for VS Code and maybe even Visual Studio?

**Comment by AaronLeoCooper** [comment]
+1

I'm so used to having it in Sublime & Atom, gorgeous theme!

**Comment by rabbit-93** [comment]
Yea, I would like to use this theme in VS code, too.

**Comment by SebastianSzturo** [comment]
Thanks for the suggestion. I will look into it this (In case no one else ported it yet). :)

**Comment by ghost** [comment]
Any progress on that? I am very interested in this. Is there a chance that you will also port the green theme? :D

**Comment by SebastianSzturo** [comment]
Krzysztof Wisznarewski already ported the theme to VS Code. You can find it here: https://gitlab.com/ulthes/firewatch-theme-vscode

**Comment by AaronLeoCooper** [comment]
Thanks for letting us know @SebastianSzturo. It's not a perfect port yet (ES6/7 syntax incomplete) but seems the author's opened an issue for that so it seems they want to make it complete in the near future.

**Comment by Ulthes** [comment]
Hey guys, I'm the guy responsible for VS Code port. I'm currently transforming it to be a native `.json` file (better support for es6 and other languages in the future). I haven't posted anything new for a while, but that's changing with this week, I'll have much more time to work on this. So, please be patient, any changes will be posted to VS Marketplace :).
