### ISSUE TITLE
🔥 to Shadow Dom

### ISSUE THREAD

**Issue by TheSeg** [SebastianSzturo/firewatch-syntax#6]
As of Atom 1.13, the Shadow DOM is [deprecated and removed](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html). This is causing the deprecation cop to yell about this syntax.

**Comment by invmatt** [comment]
Not sure if @SebastianSzturo has started this however I'll have a PR ready shortly to fix the deprecations.

PR: https://github.com/SebastianSzturo/firewatch-syntax/pull/7

**Comment by SebastianSzturo** [comment]
Sorry for the delay, just published the update. Happy updating! :)
