### ISSUE TITLE
invisible-character.eol is unstyled

### ISSUE THREAD

**Issue by SmartFinn** [SebastianSzturo/firewatch-syntax#8]
Atom 1.13.0
firewatch-syntax v1.1.0

![screenshot from 2017-01-12 11-18-15](https://cloud.githubusercontent.com/assets/819186/21883650/d893473c-d8b8-11e6-932a-9ae6f189f6bb.png)

**Comment by invmatt** [comment]
Looks like I added --syntax to the invisible character class. Will just need to be removed from `.syntax--invisible-character {` in editor.less

**Comment by h-marvin** [comment]
Same applies for white space characters. They used to be very "in the background", but are normal font color/opacity now.

**Comment by SebastianSzturo** [comment]
Thanks again for the fix. I published the updated `v1.1.1`

**Comment by invmatt** [comment]
No problem, I use it everyday so I thought it would be nice to help out. Thanks for the theme too.
